trigger: none
pr: none
variables:
  - template: pipelines/variables.yml
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    path: s/app
  - template: pipelines/azure-step.yml
    parameters:
      mode: Preview
